pandoc_common:
  output_basename: main  
  filters:
#  - pandoc-crossref
  - pandoc-citeproc
  - teaching_md
  input_files:
  - settings.yaml
## Put preambles here  
  - preamble/abstract.md
  - preamble/authorization.md
  - separators/mainmatter.md
## Include chapters here    
  - chapters/Introduction.md
  - chapters/Tecnologia USB.md
  - chapters/VUSB.md
  - chapters/Prototipo hardware.md
##- chapters/ATmega.md
  - chapters/Firmware.md
  - chapters/Drivers.md
  - chapters/Conclusiones.md
##- chapters/test_chapter.md
  - separators/backmatter.md
## Include appendices here  
  - appendices/InglesObligatorio.md
  - appendices/contribuciones.md    
  - appendices/flashCustomFirmware.md
  - appendices/monitorUSBTraffic.md
## Include this file if your document contains a bibliography  
  - separators/bibliography.md
pandoc_targets:
  PDF:
    options: -t latex -s --pdf-engine=lualatex --template=pandoc-template.tex -N --verbose --highlight-style=tango
  DOCX:
    options: -t docx
